# TASK 1
**Question 1:**

In [1]:
 def division(a, b):
    try:
        output = a/b
        print("Code Executed successfully.. The output is ", output)

    except ZeroDivisionError:
    
        print("Code Execution Failed: You are dividing by Zero..!")
    
    
division(5,0)
    

Code Execution Failed: You are dividing by Zero..!


<font color=blue>**Question 2: Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].**

**Hint: Subject,Verb and Object should be declared in the program as shown below.**

**subjects=["Americans ","Indians"]**

**verbs=["play","watch"]**

**objects=["Baseball","Cricket"]**

**Output should come as below:**

**Americans play Baseball.**

**Americans play Cricket.**

**Americans watch Baseball.**

**Americans watch Cricket.**

**Indians play Baseball.**

**Indians play Cricket.**

**Indians watch Baseball.**

**Indians watch Cricket.**</font>

In [2]:
Subjects = ['Americans', 'Indians']
Verbs = ['Play', 'Watch']
Objects = ['Baseball', 'Cricket']

for a in Subjects:
    
    for b in Verbs:
        
        for c in Objects:
            
            print(a, b, c, end=".")
            print()
            

Americans Play Baseball.
Americans Play Cricket.
Americans Watch Baseball.
Americans Watch Cricket.
Indians Play Baseball.
Indians Play Cricket.
Indians Watch Baseball.
Indians Watch Cricket.


# TASK 2

<font color=blue>**Question 1: Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.**

**HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.**</font>

In [4]:
def matrix(l):
    import numpy as np
    x = np.array(l)
    N = len(x)
    b = np.column_stack([x**(N-i-1) for i in range(0,N)])
    c = b[:, ::-1]
    print(c)
    
    
l = [1, 2, 3, 4, 5]
matrix(l)
    

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
